---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - colony.colonyos.io
  resources:
  - blueprintdefinitions
  - blueprints
  - colonyprocesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - colony.colonyos.io
  resources:
  - blueprintdefinitions/finalizers
  - blueprints/finalizers
  - colonyprocesses/finalizers
  verbs:
  - update
- apiGroups:
  - colony.colonyos.io
  resources:
  - blueprintdefinitions/status
  - blueprints/status
  - colonyprocesses/status
  verbs:
  - get
  - patch
  - update
