# Example ColonyOS credentials secret
# Copy this file, fill in your values, and apply to each namespace where you want to use Kolony
#
# kubectl apply -f colonyos-credentials.yaml -n <your-namespace>
#
apiVersion: v1
kind: Secret
metadata:
  name: colonyos-credentials
  # namespace: <your-namespace>
type: Opaque
stringData:
  serverHost: "server.colonyos.io"
  serverPort: "443"
  tls: "true"
  colonyName: "<your-colony-name>"
  executorPrvKey: "<your-executor-private-key>"
